const _products = [
  {"id": 0, "img": "1.jpg", "title": "Java - efficient programming", "body": "Lorem ipsum dolor sit amet. Ipsam voluptatem, quia consequuntur magni dolores et accusamus. Voluptatibus maiores alias consequatur aut rerum hic tenetur a sapiente. Omnis voluptas sit, amet, consectetur, adipisci velit, sed ut aut officiis debitis. Officia deserunt mollitia animi, id est eligendi optio cumque. Omnis dolor repellendus iure reprehenderit, qui blanditiis praesentium voluptatum.", "price": 12.09, "inventory": 12},
  {"id": 1, "img": "2.jpg", "title": "Python", "price": 6.53, "body": "Lorem ipsum dolor sit amet. Ipsam voluptatem, quia consequuntur magni dolores et accusamus. Voluptatibus maiores alias consequatur aut rerum hic tenetur a sapiente. Omnis voluptas sit, amet, consectetur, adipisci velit, sed ut aut officiis debitis. Officia deserunt mollitia animi, id est eligendi optio cumque. Omnis dolor repellendus iure reprehenderit, qui blanditiis praesentium voluptatum.", "inventory": 10},
  {"id": 2, "img": "4.jpg", "title": "Basics of C++", "body": "Lorem ipsum dolor sit amet. Ipsam voluptatem, quia consequuntur magni dolores et accusamus. Voluptatibus maiores alias consequatur aut rerum hic tenetur a sapiente. Omnis voluptas sit, amet, consectetur, adipisci velit, sed ut aut officiis debitis. Officia deserunt mollitia animi, id est eligendi optio cumque. Omnis dolor repellendus iure reprehenderit, qui blanditiis praesentium voluptatum.", "price": 4.99, "inventory": 18},
  {"id": 3, "img": "5.jpg", "title": "C#", "price": 24.39, "body": "Lorem ipsum dolor sit amet. Ipsam voluptatem, quia consequuntur magni dolores et accusamus. Voluptatibus maiores alias consequatur aut rerum hic tenetur a sapiente. Omnis voluptas sit, amet, consectetur, adipisci velit, sed ut aut officiis debitis. Officia deserunt mollitia animi, id est eligendi optio cumque. Omnis dolor repellendus iure reprehenderit, qui blanditiis praesentium voluptatum.", "inventory": 4},
  {"id": 4, "img": "3.jpg", "title": "JavaScript the strengths", "body": "Lorem ipsum dolor sit amet. Ipsam voluptatem, quia consequuntur magni dolores et accusamus. Voluptatibus maiores alias consequatur aut rerum hic tenetur a sapiente. Omnis voluptas sit, amet, consectetur, adipisci velit, sed ut aut officiis debitis. Officia deserunt mollitia animi, id est eligendi optio cumque. Omnis dolor repellendus iure reprehenderit, qui blanditiis praesentium voluptatum.", "price": 25.09, "inventory": 8},
  {"id": 5, "img": "6.jpg", "title": "JavaScript ES6", "body": "Lorem ipsum dolor sit amet. Ipsam voluptatem, quia consequuntur magni dolores et accusamus. Voluptatibus maiores alias consequatur aut rerum hic tenetur a sapiente. Omnis voluptas sit, amet, consectetur, adipisci velit, sed ut aut officiis debitis. Officia deserunt mollitia animi, id est eligendi optio cumque. Omnis dolor repellendus iure reprehenderit, qui blanditiis praesentium voluptatum.", "price": 17.03, "inventory": 12},
  {"id": 6, "img": "7.jpg", "title": "SOFTSWITCH", "body": "Lorem ipsum dolor sit amet. Ipsam voluptatem, quia consequuntur magni dolores et accusamus. Voluptatibus maiores alias consequatur aut rerum hic tenetur a sapiente. Omnis voluptas sit, amet, consectetur, adipisci velit, sed ut aut officiis debitis. Officia deserunt mollitia animi, id est eligendi optio cumque. Omnis dolor repellendus iure reprehenderit, qui blanditiis praesentium voluptatum.", "price": 16.98, "inventory": 2},
  {"id": 7, "img": "9.jpg", "title": "Linix terminal", "body": "Lorem ipsum dolor sit amet. Ipsam voluptatem, quia consequuntur magni dolores et accusamus. Voluptatibus maiores alias consequatur aut rerum hic tenetur a sapiente. Omnis voluptas sit, amet, consectetur, adipisci velit, sed ut aut officiis debitis. Officia deserunt mollitia animi, id est eligendi optio cumque. Omnis dolor repellendus iure reprehenderit, qui blanditiis praesentium voluptatum.", "price": 3.99, "inventory": 12},
  {"id": 8, "img": "8.jpg", "title": "Java pro", "body": "Lorem ipsum dolor sit amet. Ipsam voluptatem, quia consequuntur magni dolores et accusamus. Voluptatibus maiores alias consequatur aut rerum hic tenetur a sapiente. Omnis voluptas sit, amet, consectetur, adipisci velit, sed ut aut officiis debitis. Officia deserunt mollitia animi, id est eligendi optio cumque. Omnis dolor repellendus iure reprehenderit, qui blanditiis praesentium voluptatum.", "price": 41.34, "inventory": 1}
];


export default {
  getProducts (cb) {
    setTimeout(() => cb(_products), 100)
  },
  buyProducts (products, cb, errorCb) {}
}
